### ISSUE TITLE
Barrier not working

### ISSUE THREAD

**Issue by abhisantos** [2lstudios-mc/SquidGame#13]
The barrier is not working when set with the wand.
Players can cross the barrier location before game starts.

Is there a special way to set it?

**Comment by sammwyy** [comment]
Have the variables been placed correctly in the arena yml file?

**Comment by abhisantos** [comment]
> Have the variables been placed correctly in the arena yml file?

Fixed!
Actually not a bug.
It turned out i was setting the kill zone inside the barrier
